package com.example.myapplication.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import com.example.myapplication.data.model.AppThemeStyle

data class ThemePalettePreview(
    val topLeft: Color,
    val topRight: Color,
    val bottomLeft: Color,
    val bottomRight: Color
)

data class AppThemePalette(
    val style: AppThemeStyle,
    val preview: ThemePalettePreview,
    val light: ColorScheme,
    val dark: ColorScheme
)

private data class Surfaces(
    val background: Color,
    val surface: Color,
    val surfaceDim: Color,
    val surfaceBright: Color,
    val surfaceContainerLowest: Color,
    val surfaceContainerLow: Color,
    val surfaceContainer: Color,
    val surfaceContainerHigh: Color,
    val surfaceContainerHighest: Color,
    val surfaceVariant: Color,
    val onBackground: Color,
    val onSurface: Color,
    val onSurfaceVariant: Color,
    val outline: Color,
    val outlineVariant: Color,
    val inverseSurface: Color,
    val inverseOnSurface: Color
)

private fun palette(
    style: AppThemeStyle,
    preview: ThemePalettePreview,
    lightPrimary: Color,
    lightSecondary: Color,
    lightTertiary: Color,
    darkPrimary: Color,
    darkSecondary: Color,
    darkTertiary: Color,
    lightContainer: Color,
    darkContainer: Color,
    lightSurfaces: Surfaces,
    darkSurfaces: Surfaces
) = AppThemePalette(
    style = style,
    preview = preview,
    light = lightColorScheme(
        primary = lightPrimary,
        onPrimary = Color.White,
        primaryContainer = lightContainer,
        onPrimaryContainer = lightPrimary,
        secondary = lightSecondary,
        onSecondary = Color.White,
        secondaryContainer = lightContainer.copy(alpha = 0.72f),
        onSecondaryContainer = lightSecondary,
        tertiary = lightTertiary,
        onTertiary = Color.White,
        tertiaryContainer = lightTertiary.copy(alpha = 0.22f),
        onTertiaryContainer = lightTertiary,
        background = lightSurfaces.background,
        onBackground = lightSurfaces.onBackground,
        surface = lightSurfaces.surface,
        onSurface = lightSurfaces.onSurface,
        surfaceDim = lightSurfaces.surfaceDim,
        surfaceBright = lightSurfaces.surfaceBright,
        surfaceContainerLowest = lightSurfaces.surfaceContainerLowest,
        surfaceContainerLow = lightSurfaces.surfaceContainerLow,
        surfaceContainer = lightSurfaces.surfaceContainer,
        surfaceContainerHigh = lightSurfaces.surfaceContainerHigh,
        surfaceContainerHighest = lightSurfaces.surfaceContainerHighest,
        surfaceVariant = lightSurfaces.surfaceVariant,
        onSurfaceVariant = lightSurfaces.onSurfaceVariant,
        outline = lightSurfaces.outline,
        outlineVariant = lightSurfaces.outlineVariant,
        inverseSurface = lightSurfaces.inverseSurface,
        inverseOnSurface = lightSurfaces.inverseOnSurface,
        inversePrimary = darkPrimary
    ),
    dark = darkColorScheme(
        primary = darkPrimary,
        onPrimary = darkSurfaces.background,
        primaryContainer = darkContainer,
        onPrimaryContainer = darkPrimary,
        secondary = darkSecondary,
        onSecondary = darkSurfaces.background,
        secondaryContainer = darkSurfaces.surfaceContainerHighest,
        onSecondaryContainer = darkSecondary,
        tertiary = darkTertiary,
        onTertiary = darkSurfaces.background,
        tertiaryContainer = darkSurfaces.surfaceContainerHigh,
        onTertiaryContainer = darkTertiary,
        background = darkSurfaces.background,
        onBackground = darkSurfaces.onBackground,
        surface = darkSurfaces.surface,
        onSurface = darkSurfaces.onSurface,
        surfaceDim = darkSurfaces.surfaceDim,
        surfaceBright = darkSurfaces.surfaceBright,
        surfaceContainerLowest = darkSurfaces.surfaceContainerLowest,
        surfaceContainerLow = darkSurfaces.surfaceContainerLow,
        surfaceContainer = darkSurfaces.surfaceContainer,
        surfaceContainerHigh = darkSurfaces.surfaceContainerHigh,
        surfaceContainerHighest = darkSurfaces.surfaceContainerHighest,
        surfaceVariant = darkSurfaces.surfaceVariant,
        onSurfaceVariant = darkSurfaces.onSurfaceVariant,
        outline = darkSurfaces.outline,
        outlineVariant = darkSurfaces.outlineVariant,
        inverseSurface = darkSurfaces.inverseSurface,
        inverseOnSurface = darkSurfaces.inverseOnSurface,
        inversePrimary = lightPrimary
    )
)

val AppThemePalettes: List<AppThemePalette> = listOf(
    palette(
        style = AppThemeStyle.PURPLE,
        preview = ThemePalettePreview(
            topLeft = Color(0xFFD0BCFF),
            topRight = Color(0xFF4A4458),
            bottomLeft = Color(0xFFEFB8C8),
            bottomRight = Color(0xFF141218)
        ),
        lightPrimary = Color(0xFF6750A4),
        lightSecondary = Color(0xFF625B71),
        lightTertiary = Color(0xFF7D5260),
        darkPrimary = Color(0xFFD0BCFF),
        darkSecondary = Color(0xFFCCC2DC),
        darkTertiary = Color(0xFFEFB8C8),
        lightContainer = Color(0xFFEADDFF),
        darkContainer = Color(0xFF4F378B),
        lightSurfaces = Surfaces(
            background = Color(0xFFF7F2FA),
            surface = Color(0xFFF7F2FA),
            surfaceDim = Color(0xFFD8D3DB),
            surfaceBright = Color(0xFFF7F2FA),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFF1ECF4),
            surfaceContainer = Color(0xFFECE6F0),
            surfaceContainerHigh = Color(0xFFE6E0EA),
            surfaceContainerHighest = Color(0xFFE0DAE4),
            surfaceVariant = Color(0xFFE7E0EC),
            onBackground = Color(0xFF1C1B1F),
            onSurface = Color(0xFF1C1B1F),
            onSurfaceVariant = Color(0xFF49454F),
            outline = Color(0xFF79747E),
            outlineVariant = Color(0xFFCAC4D0),
            inverseSurface = Color(0xFF313033),
            inverseOnSurface = Color(0xFFF4EFF4)
        ),
        darkSurfaces = Surfaces(
            background = Color(0xFF141218),
            surface = Color(0xFF141218),
            surfaceDim = Color(0xFF141218),
            surfaceBright = Color(0xFF3A383E),
            surfaceContainerLowest = Color(0xFF0F0D13),
            surfaceContainerLow = Color(0xFF1C1B1F),
            surfaceContainer = Color(0xFF211F26),
            surfaceContainerHigh = Color(0xFF2B2930),
            surfaceContainerHighest = Color(0xFF36343B),
            surfaceVariant = Color(0xFF49454F),
            onBackground = Color(0xFFE6E1E5),
            onSurface = Color(0xFFE6E1E5),
            onSurfaceVariant = Color(0xFFCAC4D0),
            outline = Color(0xFF938F99),
            outlineVariant = Color(0xFF49454F),
            inverseSurface = Color(0xFFE6E1E5),
            inverseOnSurface = Color(0xFF313033)
        )
    ),
    palette(
        style = AppThemeStyle.ROSE,
        preview = ThemePalettePreview(
            topLeft = Color(0xFFFFB1C1),
            topRight = Color(0xFF5C3F46),
            bottomLeft = Color(0xFFFFD8E4),
            bottomRight = Color(0xFF1C1014)
        ),
        lightPrimary = Color(0xFF8E4A5E),
        lightSecondary = Color(0xFF72565D),
        lightTertiary = Color(0xFF7C5635),
        darkPrimary = Color(0xFFFFB1C1),
        darkSecondary = Color(0xFFE0BDC4),
        darkTertiary = Color(0xFFF0BC95),
        lightContainer = Color(0xFFFFD9E2),
        darkContainer = Color(0xFF723348),
        lightSurfaces = Surfaces(
            background = Color(0xFFFFF8F8),
            surface = Color(0xFFFFF8F8),
            surfaceDim = Color(0xFFE4D7D9),
            surfaceBright = Color(0xFFFFF8F8),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFFCF0F1),
            surfaceContainer = Color(0xFFF6EAEC),
            surfaceContainerHigh = Color(0xFFF0E4E6),
            surfaceContainerHighest = Color(0xFFEADFE1),
            surfaceVariant = Color(0xFFF3DDE2),
            onBackground = Color(0xFF22191C),
            onSurface = Color(0xFF22191C),
            onSurfaceVariant = Color(0xFF524346),
            outline = Color(0xFF847376),
            outlineVariant = Color(0xFFD6C2C6),
            inverseSurface = Color(0xFF382E31),
            inverseOnSurface = Color(0xFFFDEDF0)
        ),
        darkSurfaces = Surfaces(
            background = Color(0xFF1C1014),
            surface = Color(0xFF1C1014),
            surfaceDim = Color(0xFF1C1014),
            surfaceBright = Color(0xFF44343A),
            surfaceContainerLowest = Color(0xFF160C10),
            surfaceContainerLow = Color(0xFF25161B),
            surfaceContainer = Color(0xFF2B1C21),
            surfaceContainerHigh = Color(0xFF37262C),
            surfaceContainerHighest = Color(0xFF433137),
            surfaceVariant = Color(0xFF524346),
            onBackground = Color(0xFFF5DDE2),
            onSurface = Color(0xFFF5DDE2),
            onSurfaceVariant = Color(0xFFD6C2C6),
            outline = Color(0xFF9F8C90),
            outlineVariant = Color(0xFF524346),
            inverseSurface = Color(0xFFF5DDE2),
            inverseOnSurface = Color(0xFF382E31)
        )
    ),
    palette(
        style = AppThemeStyle.BLUE,
        preview = ThemePalettePreview(
            topLeft = Color(0xFFADC6FF),
            topRight = Color(0xFF3F4759),
            bottomLeft = Color(0xFFD6E3FF),
            bottomRight = Color(0xFF111318)
        ),
        lightPrimary = Color(0xFF3B5BA9),
        lightSecondary = Color(0xFF565E71),
        lightTertiary = Color(0xFF705574),
        darkPrimary = Color(0xFFADC6FF),
        darkSecondary = Color(0xFFBEC6DC),
        darkTertiary = Color(0xFFDABDE0),
        lightContainer = Color(0xFFDAE2FF),
        darkContainer = Color(0xFF21428F),
        lightSurfaces = Surfaces(
            background = Color(0xFFF8F9FF),
            surface = Color(0xFFF8F9FF),
            surfaceDim = Color(0xFFD8DAE4),
            surfaceBright = Color(0xFFF8F9FF),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFF2F3FD),
            surfaceContainer = Color(0xFFECEDF7),
            surfaceContainerHigh = Color(0xFFE6E8F1),
            surfaceContainerHighest = Color(0xFFE0E2EC),
            surfaceVariant = Color(0xFFE0E2EC),
            onBackground = Color(0xFF191C20),
            onSurface = Color(0xFF191C20),
            onSurfaceVariant = Color(0xFF44474E),
            outline = Color(0xFF74777F),
            outlineVariant = Color(0xFFC4C6D0),
            inverseSurface = Color(0xFF2E3036),
            inverseOnSurface = Color(0xFFF0F0FA)
        ),
        darkSurfaces = Surfaces(
            background = Color(0xFF111318),
            surface = Color(0xFF111318),
            surfaceDim = Color(0xFF111318),
            surfaceBright = Color(0xFF37393F),
            surfaceContainerLowest = Color(0xFF0C0E13),
            surfaceContainerLow = Color(0xFF191C20),
            surfaceContainer = Color(0xFF1D2024),
            surfaceContainerHigh = Color(0xFF282A2F),
            surfaceContainerHighest = Color(0xFF33353A),
            surfaceVariant = Color(0xFF44474E),
            onBackground = Color(0xFFE2E2EC),
            onSurface = Color(0xFFE2E2EC),
            onSurfaceVariant = Color(0xFFC4C6D0),
            outline = Color(0xFF8E9099),
            outlineVariant = Color(0xFF44474E),
            inverseSurface = Color(0xFFE2E2EC),
            inverseOnSurface = Color(0xFF2E3036)
        )
    ),
    palette(
        style = AppThemeStyle.TEAL,
        preview = ThemePalettePreview(
            topLeft = Color(0xFF82D5C8),
            topRight = Color(0xFF3A4A47),
            bottomLeft = Color(0xFFB1EFE4),
            bottomRight = Color(0xFF0E1514)
        ),
        lightPrimary = Color(0xFF006A60),
        lightSecondary = Color(0xFF4A635F),
        lightTertiary = Color(0xFF456179),
        darkPrimary = Color(0xFF82D5C8),
        darkSecondary = Color(0xFFB0CCC6),
        darkTertiary = Color(0xFFADCBE6),
        lightContainer = Color(0xFF83F4E5),
        darkContainer = Color(0xFF005048),
        lightSurfaces = Surfaces(
            background = Color(0xFFF4FBFA),
            surface = Color(0xFFF4FBFA),
            surfaceDim = Color(0xFFD5DBDA),
            surfaceBright = Color(0xFFF4FBFA),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFEEF5F4),
            surfaceContainer = Color(0xFFE8EFEE),
            surfaceContainerHigh = Color(0xFFE2E9E8),
            surfaceContainerHighest = Color(0xFFDCE3E2),
            surfaceVariant = Color(0xFFDAE5E2),
            onBackground = Color(0xFF161D1C),
            onSurface = Color(0xFF161D1C),
            onSurfaceVariant = Color(0xFF3F4947),
            outline = Color(0xFF6F7977),
            outlineVariant = Color(0xFFBEC9C6),
            inverseSurface = Color(0xFF2B3231),
            inverseOnSurface = Color(0xFFECF2F0)
        ),
        darkSurfaces = Surfaces(
            background = Color(0xFF0E1514),
            surface = Color(0xFF0E1514),
            surfaceDim = Color(0xFF0E1514),
            surfaceBright = Color(0xFF343B3A),
            surfaceContainerLowest = Color(0xFF09100F),
            surfaceContainerLow = Color(0xFF161D1C),
            surfaceContainer = Color(0xFF1A2120),
            surfaceContainerHigh = Color(0xFF252B2A),
            surfaceContainerHighest = Color(0xFF2F3635),
            surfaceVariant = Color(0xFF3F4947),
            onBackground = Color(0xFFDDE4E2),
            onSurface = Color(0xFFDDE4E2),
            onSurfaceVariant = Color(0xFFBEC9C6),
            outline = Color(0xFF899390),
            outlineVariant = Color(0xFF3F4947),
            inverseSurface = Color(0xFFDDE4E2),
            inverseOnSurface = Color(0xFF2B3231)
        )
    ),
    palette(
        style = AppThemeStyle.GREEN,
        preview = ThemePalettePreview(
            topLeft = Color(0xFF4AE174),
            topRight = Color(0xFF384B3E),
            bottomLeft = Color(0xFF6CFF95),
            bottomRight = Color(0xFF0F1510)
        ),
        lightPrimary = Color(0xFF006E2C),
        lightSecondary = Color(0xFF506355),
        lightTertiary = Color(0xFF3B6471),
        darkPrimary = Color(0xFF4AE174),
        darkSecondary = Color(0xFFB6CCBB),
        darkTertiary = Color(0xFFA3CDDC),
        lightContainer = Color(0xFF6CFF95),
        darkContainer = Color(0xFF005320),
        lightSurfaces = Surfaces(
            background = Color(0xFFF6FBF3),
            surface = Color(0xFFF6FBF3),
            surfaceDim = Color(0xFFD6DCD5),
            surfaceBright = Color(0xFFF6FBF3),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFF0F5ED),
            surfaceContainer = Color(0xFFEAEFE7),
            surfaceContainerHigh = Color(0xFFE4E9E1),
            surfaceContainerHighest = Color(0xFFDEE3DC),
            surfaceVariant = Color(0xFFDCE5DA),
            onBackground = Color(0xFF171D18),
            onSurface = Color(0xFF171D18),
            onSurfaceVariant = Color(0xFF414941),
            outline = Color(0xFF717971),
            outlineVariant = Color(0xFFC0C9BE),
            inverseSurface = Color(0xFF2C322C),
            inverseOnSurface = Color(0xFFEDF2EA)
        ),
        darkSurfaces = Surfaces(
            background = Color(0xFF0F1510),
            surface = Color(0xFF0F1510),
            surfaceDim = Color(0xFF0F1510),
            surfaceBright = Color(0xFF353B35),
            surfaceContainerLowest = Color(0xFF0A100B),
            surfaceContainerLow = Color(0xFF171D18),
            surfaceContainer = Color(0xFF1B211C),
            surfaceContainerHigh = Color(0xFF262C26),
            surfaceContainerHighest = Color(0xFF303731),
            surfaceVariant = Color(0xFF414941),
            onBackground = Color(0xFFDFE4DC),
            onSurface = Color(0xFFDFE4DC),
            onSurfaceVariant = Color(0xFFC0C9BE),
            outline = Color(0xFF8B9389),
            outlineVariant = Color(0xFF414941),
            inverseSurface = Color(0xFFDFE4DC),
            inverseOnSurface = Color(0xFF2C322C)
        )
    ),
    palette(
        style = AppThemeStyle.AMBER,
        preview = ThemePalettePreview(
            topLeft = Color(0xFFFFB95F),
            topRight = Color(0xFF4A453A),
            bottomLeft = Color(0xFFFFDCB2),
            bottomRight = Color(0xFF1A1612)
        ),
        lightPrimary = Color(0xFF855300),
        lightSecondary = Color(0xFF6F5B40),
        lightTertiary = Color(0xFF516440),
        darkPrimary = Color(0xFFFFB95F),
        darkSecondary = Color(0xFFDCC3A1),
        darkTertiary = Color(0xFFB8CBA0),
        lightContainer = Color(0xFFFFDDB3),
        darkContainer = Color(0xFF653E00),
        lightSurfaces = Surfaces(
            background = Color(0xFFFFF8F3),
            surface = Color(0xFFFFF8F3),
            surfaceDim = Color(0xFFE4D8CC),
            surfaceBright = Color(0xFFFFF8F3),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFFCF1E8),
            surfaceContainer = Color(0xFFF6EBE2),
            surfaceContainerHigh = Color(0xFFF0E5DC),
            surfaceContainerHighest = Color(0xFFEADFD6),
            surfaceVariant = Color(0xFFEDE0D0),
            onBackground = Color(0xFF1F1B16),
            onSurface = Color(0xFF1F1B16),
            onSurfaceVariant = Color(0xFF4E4539),
            outline = Color(0xFF807567),
            outlineVariant = Color(0xFFD1C5B4),
            inverseSurface = Color(0xFF352F29),
            inverseOnSurface = Color(0xFFF9EFE6)
        ),
        darkSurfaces = Surfaces(
            background = Color(0xFF1A1612),
            surface = Color(0xFF1A1612),
            surfaceDim = Color(0xFF1A1612),
            surfaceBright = Color(0xFF413C36),
            surfaceContainerLowest = Color(0xFF14110D),
            surfaceContainerLow = Color(0xFF221E19),
            surfaceContainer = Color(0xFF27231E),
            surfaceContainerHigh = Color(0xFF322D27),
            surfaceContainerHighest = Color(0xFF3D3832),
            surfaceVariant = Color(0xFF4E4539),
            onBackground = Color(0xFFEDE0D0),
            onSurface = Color(0xFFEDE0D0),
            onSurfaceVariant = Color(0xFFD1C5B4),
            outline = Color(0xFF9A8F80),
            outlineVariant = Color(0xFF4E4539),
            inverseSurface = Color(0xFFEDE0D0),
            inverseOnSurface = Color(0xFF352F29)
        )
    ),
    palette(
        style = AppThemeStyle.ORCHID,
        preview = ThemePalettePreview(
            topLeft = Color(0xFFE5B6FF),
            topRight = Color(0xFF4B4054),
            bottomLeft = Color(0xFFF6D9FF),
            bottomRight = Color(0xFF17121B)
        ),
        lightPrimary = Color(0xFF7B4E9E),
        lightSecondary = Color(0xFF68596D),
        lightTertiary = Color(0xFF82524C),
        darkPrimary = Color(0xFFE5B6FF),
        darkSecondary = Color(0xFFD3C1D7),
        darkTertiary = Color(0xFFF6B8AF),
        lightContainer = Color(0xFFF3DAFF),
        darkContainer = Color(0xFF613686),
        lightSurfaces = Surfaces(
            background = Color(0xFFFEF7FF),
            surface = Color(0xFFFEF7FF),
            surfaceDim = Color(0xFFDED6E4),
            surfaceBright = Color(0xFFFEF7FF),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFF8F0FC),
            surfaceContainer = Color(0xFFF2EAF6),
            surfaceContainerHigh = Color(0xFFECE4F0),
            surfaceContainerHighest = Color(0xFFE6DEF0),
            surfaceVariant = Color(0xFFEBDDF0),
            onBackground = Color(0xFF1D1A22),
            onSurface = Color(0xFF1D1A22),
            onSurfaceVariant = Color(0xFF4B4450),
            outline = Color(0xFF7C7481),
            outlineVariant = Color(0xFFCDC2D2),
            inverseSurface = Color(0xFF322F37),
            inverseOnSurface = Color(0xFFF6EEFA)
        ),
        darkSurfaces = Surfaces(
            background = Color(0xFF17121B),
            surface = Color(0xFF17121B),
            surfaceDim = Color(0xFF17121B),
            surfaceBright = Color(0xFF3E3843),
            surfaceContainerLowest = Color(0xFF120D16),
            surfaceContainerLow = Color(0xFF1D1A22),
            surfaceContainer = Color(0xFF221E26),
            surfaceContainerHigh = Color(0xFF2C2831),
            surfaceContainerHighest = Color(0xFF37333C),
            surfaceVariant = Color(0xFF4B4450),
            onBackground = Color(0xFFE8DFEE),
            onSurface = Color(0xFFE8DFEE),
            onSurfaceVariant = Color(0xFFCDC2D2),
            outline = Color(0xFF968D9B),
            outlineVariant = Color(0xFF4B4450),
            inverseSurface = Color(0xFFE8DFEE),
            inverseOnSurface = Color(0xFF322F37)
        )
    ),
    palette(
        style = AppThemeStyle.MAUVE,
        preview = ThemePalettePreview(
            topLeft = Color(0xFFE6B8C6),
            topRight = Color(0xFF4A4144),
            bottomLeft = Color(0xFFFFD9E3),
            bottomRight = Color(0xFF181214)
        ),
        lightPrimary = Color(0xFF7C5260),
        lightSecondary = Color(0xFF6F585D),
        lightTertiary = Color(0xFF7A5734),
        darkPrimary = Color(0xFFE6B8C6),
        darkSecondary = Color(0xFFD9BFC5),
        darkTertiary = Color(0xFFEDBC90),
        lightContainer = Color(0xFFFFD9E3),
        darkContainer = Color(0xFF623B49),
        lightSurfaces = Surfaces(
            background = Color(0xFFFFF8F8),
            surface = Color(0xFFFFF8F8),
            surfaceDim = Color(0xFFE3D7D9),
            surfaceBright = Color(0xFFFFF8F8),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFFCF1F2),
            surfaceContainer = Color(0xFFF6EBEC),
            surfaceContainerHigh = Color(0xFFF0E5E6),
            surfaceContainerHighest = Color(0xFFEADFE0),
            surfaceVariant = Color(0xFFEDDDE1),
            onBackground = Color(0xFF201A1C),
            onSurface = Color(0xFF201A1C),
            onSurfaceVariant = Color(0xFF524346),
            outline = Color(0xFF847376),
            outlineVariant = Color(0xFFD6C2C6),
            inverseSurface = Color(0xFF362F31),
            inverseOnSurface = Color(0xFFFBEEF0)
        ),
        darkSurfaces = Surfaces(
            background = Color(0xFF181214),
            surface = Color(0xFF181214),
            surfaceDim = Color(0xFF181214),
            surfaceBright = Color(0xFF3F3739),
            surfaceContainerLowest = Color(0xFF130E10),
            surfaceContainerLow = Color(0xFF201A1C),
            surfaceContainer = Color(0xFF251E20),
            surfaceContainerHigh = Color(0xFF2F282A),
            surfaceContainerHighest = Color(0xFF3A3335),
            surfaceVariant = Color(0xFF524346),
            onBackground = Color(0xFFEEDFE2),
            onSurface = Color(0xFFEEDFE2),
            onSurfaceVariant = Color(0xFFD6C2C6),
            outline = Color(0xFF9E8C90),
            outlineVariant = Color(0xFF524346),
            inverseSurface = Color(0xFFEEDFE2),
            inverseOnSurface = Color(0xFF362F31)
        )
    )
)

fun AppThemeStyle.palette(): AppThemePalette =
    AppThemePalettes.firstOrNull { it.style == this } ?: AppThemePalettes.first()
